# Generated by Django 4.2.30 on 2026-06-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_amount_budget_limit_amount_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
